 //This file is automatically generated. Do not edit it directly.
 import { createClient } from '@supabase/supabase-js';
 import type { Database } from './types';

 const SUPABASE_URL = "https://enkocfsuqpwhkhcsqosr.supabase.co";
 const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVua29jZnN1cXB3aGtoY3Nxb3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNzM2NzQsImV4cCI6MjA3NjY0OTY3NH0.6tC368DM6BWY3ueAg3BqBsefmNQHEFsgGVj21dMkdHU";

 // Import the supabase client like this:
 // import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);